import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { usersTable } from "./users";
import {
  operationalAlertTypeEnum,
  alertSeverityEnum,
  alertStatusEnum,
} from "./enums";

/**
 * operational_alerts — governance and compliance alerts generated by the
 * alert detection engine. Each row represents one actionable issue.
 *
 * alertCode is a deterministic key used for idempotency:
 *   format: <alertType>:<projectId>:<entityType>:<entityRef>
 *   Only one open alert per unique alertCode is kept — re-runs skip existing open alerts.
 *
 * metadata stores the raw detection context as JSONB for audit review.
 */
export const operationalAlertsTable = pgTable("operational_alerts", {
  id: uuid("id").primaryKey().defaultRandom(),

  alertCode: text("alert_code").notNull(),
  alertType: operationalAlertTypeEnum("alert_type").notNull(),
  severity: alertSeverityEnum("severity").notNull(),
  status: alertStatusEnum("status").notNull().default("open"),

  title: text("title").notNull(),
  description: text("description").notNull(),

  projectId: uuid("project_id").references(() => projectsTable.id, {
    onDelete: "set null",
  }),
  projectName: text("project_name"),

  entityType: text("entity_type"),
  entityId: uuid("entity_id"),
  entityRef: text("entity_ref"),

  detectedAt: timestamp("detected_at", { withTimezone: true })
    .notNull()
    .defaultNow(),

  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  acknowledgedById: uuid("acknowledged_by_id").references(() => usersTable.id, {
    onDelete: "set null",
  }),
  acknowledgedByName: text("acknowledged_by_name"),

  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  resolvedById: uuid("resolved_by_id").references(() => usersTable.id, {
    onDelete: "set null",
  }),
  resolvedByName: text("resolved_by_name"),
  resolutionNotes: text("resolution_notes"),

  metadata: jsonb("metadata"),

  isActive: boolean("is_active").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
