/**
 * report_export_jobs.ts
 *
 * Tracks every report export request — PDF or Excel — generated by the system.
 * Stores job metadata, status, and the GCS object path of the generated file.
 *
 * Lifecycle:
 *   queued → generating → completed | failed
 *
 * Files expire after 7 days (expiresAt). Expired jobs are kept for audit history
 * but their fileObjectPath is no longer accessible.
 */
import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { usersTable } from "./users";

export const reportExportJobsTable = pgTable("report_export_jobs", {
  id: uuid("id").primaryKey().defaultRandom(),

  // ── Requester ──────────────────────────────────────────────────────────────
  userId: uuid("user_id").references(() => usersTable.id, { onDelete: "set null" }),
  userName: text("user_name"),
  userRole: text("user_role"),

  // ── Report spec ────────────────────────────────────────────────────────────
  // financial | project | ownership | distribution | inventory | governance
  reportType: text("report_type").notNull(),
  // pdf | excel
  exportFormat: text("export_format").notNull(),

  // ── Scope ──────────────────────────────────────────────────────────────────
  projectId: uuid("project_id").references(() => projectsTable.id, { onDelete: "set null" }),
  projectName: text("project_name"),

  // ISO date strings "YYYY-MM-DD"
  dateStart: text("date_start"),
  dateEnd: text("date_end"),

  // Extra filter options (e.g. partner, module, severity)
  filters: jsonb("filters"),

  // ── Status ─────────────────────────────────────────────────────────────────
  // queued | generating | completed | failed | expired
  status: text("status").notNull().default("queued"),

  // ── Generated file ─────────────────────────────────────────────────────────
  fileName: text("file_name"),
  fileObjectPath: text("file_object_path"),
  fileSizeBytes: integer("file_size_bytes"),
  mimeType: text("mime_type"),

  errorMessage: text("error_message"),

  generatedAt: timestamp("generated_at", { withTimezone: true }),

  // ── Download tracking ──────────────────────────────────────────────────────
  downloadCount: integer("download_count").notNull().default(0),
  lastDownloadedAt: timestamp("last_downloaded_at", { withTimezone: true }),

  // ── Expiry ─────────────────────────────────────────────────────────────────
  expiresAt: timestamp("expires_at", { withTimezone: true }),

  isActive: boolean("is_active").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ReportExportJob = typeof reportExportJobsTable.$inferSelect;
export type ReportExportJobInsert = typeof reportExportJobsTable.$inferInsert;
