/**
 * sale_event_journal.ts
 *
 * V3 Partner Financial Ledger — Wave 1 (schema only).
 *
 * Envelope log of Sale Rubber domain events. Write-once. Drives the
 * revenue handler in Wave 3. event_id is generated by the emitter and
 * MUST be unique.
 *
 * Event types:
 *   SaleFinanciallyRecognized
 *   SaleCancelled
 *   InternalPartnerPurchaseCompleted
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { projectsTable } from "./projects";

export const saleEventJournalTable = pgTable(
  "sale_event_journal",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /** Caller-generated UUID; UNIQUE; used by idempotent dispatcher. */
    eventId: uuid("event_id").notNull(),

    /** SaleFinanciallyRecognized | SaleCancelled | InternalPartnerPurchaseCompleted */
    eventType: text("event_type").notNull(),

    projectId: uuid("project_id")
      .notNull()
      .references(() => projectsTable.id, { onDelete: "restrict" }),

    /** sales_transaction | sales_order */
    saleReferenceType: text("sale_reference_type").notNull(),
    saleReferenceId: uuid("sale_reference_id").notNull(),

    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),

    /** Full event payload — handler input. */
    payload: jsonb("payload").notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    uniqueEventId: uniqueIndex("sej_event_id_uq").on(t.eventId),
    bySale: index("sej_sale_idx").on(t.saleReferenceType, t.saleReferenceId),
    byType: index("sej_type_idx").on(t.eventType),
    eventTypeValid: check(
      "sej_event_type_chk",
      sql`${t.eventType} IN (
        'SaleFinanciallyRecognized','SaleCancelled','InternalPartnerPurchaseCompleted'
      )`,
    ),
    saleRefValid: check(
      "sej_sale_ref_chk",
      sql`${t.saleReferenceType} IN ('sales_transaction','sales_order')`,
    ),
  }),
);

export type SaleEventJournal = typeof saleEventJournalTable.$inferSelect;
export type SaleEventJournalInsert =
  typeof saleEventJournalTable.$inferInsert;
