/**
 * saleEvents/publish.ts
 *
 * V3 Wave 2 — Sale-event publication helper.
 *
 * Flag-gated. Idempotent via UNIQUE(event_id) on sale_event_journal.
 * Wave 2 has zero callers; downstream waves will invoke this from the
 * same transaction that performs the sale state transition (transactional
 * outbox pattern).
 *
 * No business logic. No side effects beyond inserting a row into
 * sale_event_journal when the flag is enabled.
 */

import { sql } from "drizzle-orm";
import { saleEventJournalTable } from "@workspace/db/schema";
import { getFinFlag } from "../featureFlags.js";
import {
  saleEventEnvelopeSchema,
  type SaleEventEnvelope,
} from "./schemas.js";

/**
 * Optional pre-computed event_id (uuid). If omitted, a uuidv4 is
 * generated by the DB via gen_random_uuid(). Callers performing
 * deterministic idempotency should pre-compute (e.g. uuidv5 over a
 * stable natural key).
 */
export type PublishSaleEventInput = SaleEventEnvelope & {
  eventId?: string;
};

export type PublishSaleEventResult =
  | { created: true; eventId: string; reason: "inserted" }
  | { created: false; eventId: string | null; reason: "duplicate" }
  | { created: false; eventId: null; reason: "flag_disabled" }
  | { created: false; eventId: null; reason: "validation_failed"; issues: unknown };

/**
 * Drizzle-compatible db handle. Accepts both the base pg database and a
 * transaction handle, since callers will typically invoke this from
 * within `db.transaction(...)`.
 */
type DbHandle = {
  execute: (query: ReturnType<typeof sql>) => Promise<{
    rows: Array<{ event_id: string }>;
  }>;
};

export async function publishSaleEvent(
  db: DbHandle,
  input: PublishSaleEventInput,
): Promise<PublishSaleEventResult> {
  if (!getFinFlag("FIN_SALE_EVENT_EMISSION_ENABLED")) {
    return { created: false, eventId: null, reason: "flag_disabled" };
  }

  const parsed = saleEventEnvelopeSchema.safeParse(input);
  if (!parsed.success) {
    return {
      created: false,
      eventId: null,
      reason: "validation_failed",
      issues: parsed.error.issues,
    };
  }

  const envelope = parsed.data;
  const providedEventId = input.eventId ?? null;
  const payloadJson = JSON.stringify(envelope.payload);

  const result = await db.execute(sql`
    INSERT INTO ${saleEventJournalTable}
      (event_id, event_type, project_id, sale_reference_type,
       sale_reference_id, occurred_at, payload)
    VALUES (
      COALESCE(${providedEventId}::uuid, gen_random_uuid()),
      ${envelope.eventType},
      ${envelope.projectId}::uuid,
      ${envelope.saleReferenceType},
      ${envelope.saleReferenceId}::uuid,
      ${envelope.occurredAt}::timestamptz,
      ${payloadJson}::jsonb
    )
    ON CONFLICT (event_id) DO NOTHING
    RETURNING event_id
  `);

  const row = result.rows[0];
  if (row) {
    return { created: true, eventId: row.event_id, reason: "inserted" };
  }
  return { created: false, eventId: providedEventId, reason: "duplicate" };
}
